

require "bit_array"

module Hypergrug
  VERSION = "0.2.0"

  # A fixed-size, hyperdimensional binary vector optimized for Vector Symbolic
  # Architecture (VSA).
  #
  # Hypervectors live in a sparse, high-dim binary vector space
  # (typically D ≥ 10,000). At this scale, random vectors are
  # quasi-orthogonal, allowing holographic data composition through bitwise ops.
  #
  # By quasi-orthogonal, we mean it's not strictly mathematically orthogonal, 
  # and the dot product probably won't come out to exactly zero, but
  # it's good enough for government work.
  #
  # In practice, the quasi-orthogonal property ensures that any random vector
  # generated with D ~= 10,000 is unique and automatically completely different
  # from any other vector generated by the system.
  # We can generate identities in different places without central coordination,
  # and it means that we can treat a hypervector as a KV store, and stick a
  # bunch of values in that don't share structural patterns. They occupy the
  # same space but don't blend their identities.
  #
  # By holographic data composition, we are referring to the concept of
  # Holographic Reduced Representations introduced by Tony Plate in the 90's,
  # who was building on Karl Pribram's holographic brain theory.
  #
  # In practice, it means data is distributed across all bits of the vector,
  # and we can superimpose multiple pieces of information in the vector while
  # still being able to pull a sharp identity out using an inverse key.
  # Holographic data composition may also be known as Distributed Semantic
  # Representation, or Vector Superposition, or Information Pooling / 
  # Aggregation, but ... holographic sounds cooler.
  #
  # Implementation uses a `struct` because it's stack-allocated, allowing
  # cache-locality predictability and avoiding gahbage collection overhead.
  #
  # ### Examples
  #
  # ```
  # # Create new orthogonal vectors
  # a = Hypervector.random(10_000)
  # b = Hypervector.random(10_000)
  #
  # # Bind keys to values via XOR
  # key_value_product = a * b
  #
  # # Bundle facts into a single vector via Majority Rule
  # memory_cache = Hypervector.bundle([a, b])
  # ```
  struct Hypervector
    # Returns the underlying raw `BitArray` representation of the hypervector.
    getter bits : BitArray

    # Returns the total dimensionality (D) of the hypervector space.
    getter dimensions : Int32

    # Initializes a zeroed hypervector of the specified dimensionality.
    #
    # All bits default to `false` (0).
    def initialize(@dimensions : Int32)
      @bits = BitArray.new(@dimensions)
    end

    # Initializes a hypervector directly from an existing `BitArray`.
    #
    # The dimensionality is automatically inferred from the size of the provided array.
    def initialize(@bits : BitArray)
      @dimensions = @bits.size
    end

    # Generates a pristine, pseudo-random hypervector where each bit has an equal
    # probability of being `true` or `false`.
    #
    # Randomly generated vectors in high dimensions ($D \ge 10,000$) are mathematically
    # guaranteed to be orthogonal to one another, preventing concept collision.
    def self.random(dimensions : Int32) : self
      hv = new(dimensions)
      r = Random.new
      dimensions.times { |ii| hv.bits[ii] = r.next_bool }
      hv
    end

    # BINDING: Combines two hypervectors into a completely new, orthogonal vector using a bitwise XOR.
    #
    # Binding is fully invertible, meaning multiplying the result by one of the original components
    # projects the other component back out (obscured by background noise if bundled).
    #
    # Raises `ArgumentError` if the dimensions of `other` do not match.
    def *(other : self) : self
      raise ArgumentError.new("Dimension mismatch") if @dimensions != other.dimensions

      result = BitArray.new(@dimensions)
      @dimensions.times { |ii| result[ii] = @bits[ii] ^ other.bits[ii] }
      Hypervector.new(result)
    end

    # BUNDLING: Superposes two hypervectors into a single vector using a Majority Rule bit-count.
    #
    # This acts as an ergonomic shortcut for binary array bundling. Even arrays ($N=2$)
    # utilize a stochastic coin-flip to resolve exact ties at individual bit positions.
    #
    # Raises `ArgumentError` if the dimensions of `other` do not match.
    def +(other : self) : self
      Hypervector.bundle([self, other])
    end

    # General $N$-ary bundling that superposes an arbitrary array of hypervectors into a single,
    # holographic representation using Majority Rule bit-counting.
    #
    # The resulting vector retains geometric similarity to all its constituent parts until
    # hitting the capacity wall ($\sim 20$–$50$ distinct items per 10,000 bits).
    #
    # If an even number of vectors are passed and a bit position has an exact tie, a stochastic
    # tie-breaker (coin-flip) is applied to prevent bitwise saturation.
    #
    # Raises `ArgumentError` if the provided array is empty.
    def self.bundle(vectors : Array(self)) : self
      raise ArgumentError.new("Cannot bundle empty array") if vectors.empty?

      dim = vectors.first.dimensions
      result = BitArray.new(dim)
      halfway = vectors.size / 2.0

      dim.times do |ii|
        true_count = vectors.count { |v| v.bits[ii] }

        if true_count == halfway
          result[ii] = Random.new.next_bool
        else
          result[ii] = true_count > halfway
        end
      end

      Hypervector.new(result)
    end

    # Computes the Hamming distance between this hypervector and `other`.
    #
    # The Hamming distance represents the total number of bit-positions that differ between
    # the two vectors. It serves as the primary proximity metric for the associative Clean-Up Memory.
    #
    # Raises `ArgumentError` if the dimensions of `other` do not match.
    def distance_to(other : self) : Int32
      raise ArgumentError.new("Dimension mismatch") if @dimensions != other.dimensions

      dist = 0
      @dimensions.times do |ii|
        dist += 1 if @bits[ii] ^ other.bits[ii]
      end
      dist
    end
  end # -----------------------------------------------------------------------

  # Clean-Up Memory to hold known concepts and provide nearest-neighbor
  # matching via "clean up snap"
  #
  # To create a memory bank:
  #
  # ```
  # vector_size = 10_000
  # memory = Hypergrug::Memory.new
  # hearth = memory.register("hearth", vector_size)
  # fire = memory.register("fire", vector_size)
  # ```
  #
  # The `#register` method returns a Hypervector for immediate use in binding
  # and bundling, and a copy of the hypervector is stored in memory for later
  # snapping to best match using `#match` method.
  class Memory
    getter registry : Hash(String, Hypervector)

    def initialize
      @registry = {} of String => Hypervector
    end

    # Generate a random vector, save it, and return it
    def register(name : String, dimensions : Int32) : Hypervector
      hv = Hypervector.random(dimensions)
      @registry[name] = hv
      hv
    end

    # Manually save an existing vector
    def add(name : String, vector : Hypervector)
      @registry[name] = vector
    end

    # The Cleanup Snap
    def match(query_vector : Hypervector) : NamedTuple(name: String, distance: Int32)?
      return nil if @registry.empty?

      best_match = nil
      # Using Hamming distance calculation - if D = 10_000, the maximum
      # possible distance between any two vectors is 10_000. (Worst case, every
      # single bit is flipped opposite). By adding 1, we start with a distance
      # that is guaranteed to be larger than anything we will find while
      # loooping.
      min_dist = query_vector.dimensions + 1

      @registry.each do |name, clean_vec|
        dist = query_vector.distance_to(clean_vec)
        if dist < min_dist
          min_dist = dist
          best_match = {name: name, distance: dist}
        end
      end

      return best_match
    end
  end # ------------------------------------------------------------------------
end
